### ISSUE TITLE
Sidewalk tags not continued on new way attached to other sidewalks while in Sidewalk mode

### ISSUE THREAD

**Issue by watmildon** [tsmock/sidewalks#2]
This is probably because you want it to be a replacement for the general draw but here's a situation I've hit a few times where I think it _could_ do the right thing.

I draw things in this order and the third way doesn't end up with any tags.

![image](https://github.com/tsmock/sidewalks/assets/118567155/55534e31-4018-4d88-897f-5bf0ca94d31b)

**Comment by tsmock** [comment]
[[NeedInfo]]
What version of the plugin are you running? v54 _should_ fix that.

**Comment by tsmock** [comment]
I wasn't able to reproduce. @watmildon : Feel free to reopen if you are still encountering it.
