### ISSUE TITLE
Creating a crosswalk to close a loop causes the first node of the way to be deleted

### ISSUE THREAD

**Issue by watmildon** [tsmock/sidewalks#3]
This way:
![image](https://github.com/tsmock/sidewalks/assets/118567155/91423916-2053-43d5-82ef-8190fb319584)
This crossing:
![image](https://github.com/tsmock/sidewalks/assets/118567155/56b96fcd-cbeb-4310-9b75-36be2d1646e4)
The weird result:
![image](https://github.com/tsmock/sidewalks/assets/118567155/aca4d4fa-8a43-4b66-8a72-bcec372f0a48)
My JOZ file with the layer in it:
[SidewalkPlugin-WeirdDelete.zip](https://github.com/tsmock/sidewalks/files/15019662/SidewalkPlugin-WeirdDelete.zip)

**Comment by watmildon** [comment]
I have my length setting upped to 30 if that makes any difference.

**Comment by tsmock** [comment]
> I have my length setting upped to 30 if that makes any difference.

It shouldn't have. And I upped the default length to 30 in v54 anyway.

**Comment by watmildon** [comment]
Okay perfect. I'm on 56 now and it doesn't repro. I hadn't restarted after updating my plugins on my first try.
