### ISSUE TITLE
Crossing ways getting attached to inner roundabout

### ISSUE THREAD

**Issue by watmildon** [tsmock/sidewalks#9]
It's very common here in Seattle for a small junction to have a mini roundabout drawn into it. This causes the plugin to find a nearest node for the crossing that happens to be on the roundabout. These are all tagged as highway=roundabout so maybe don't attach to them? Maybe it should be? Dunno.

![image](https://github.com/tsmock/sidewalks/assets/118567155/fbbc601c-27e1-4914-a727-7264719623a9)

**Comment by tsmock** [comment]
I did not think about roundabouts. Thanks for the bug report.
I'll probably do a check to make certain that the node isn't the first/last node.
